### ISSUE TITLE
How does the code handle objects which go out from the image and return inside afterwards?

### ISSUE THREAD

**Issue by andreazuna89** [mikel-brostrom/yolov8_tracking#739]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Thanks for the great work! I have noticed that when I run the tracking code on a webcam source for example, if an object goes out from the field of the image and then returns inside afterwards very rarely the previous ID is assigned again to it. Indeed in general the ID is incremented and becomes different. Does the algorithm consider these cases or maybe do you believe there could be a possible improvement on it? Of course, I understand that this is a more challenging scenario to tackle.

Thanks a lot

**Comment by turinaf** [comment]
Yeah, ID changes, even when a person is covered with another person for a very short time while in camera frame. 

It would be good idea if it's possible to reserve the assigned ID and check if the new detected person is same as the previously detected one before assigning new ID to it (maybe extracting features using reid model and calculating similarity). If the new detected person is same as the previously detected one or same as the one detected in another camera(incase of multi camera tracking), give same ID. Otherwise increment ID and assign new ID. @mikel-brostrom 

It sounds challenging tho.

**Comment by henriksod** [comment]
Hi! I have attempted to tackle this problem in #626

I am trying to save the features of a previously lost track and try to associate "dead" features with new detections such that they can hopefully be re-associated when an object re-appears in frame after being lost.

It is not fully working as intended, but the code is there so maybe you can review it and come up with some ideas.
